version: '3.8'

services:
  ambev.developerevaluation.webapi:
    container_name: ambev_developer_evaluation_webapi
    image: ${DOCKER_REGISTRY-}ambevdeveloperevaluationwebapi
    build:
      context: .
      dockerfile: src/Ambev.DeveloperEvaluation.WebApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    networks:
      - ambev_network
    depends_on:
      - ambev.developerevaluation.database
      - ambev.developerevaluation.nosql
      - ambev.developereevaluation.rabbitmq
    restart: unless-stopped

  ambev.developerevaluation.database:
    container_name: ambev_developer_evaluation_database
    image: postgres:13
    environment:
      POSTGRES_DB: developer_evaluation
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: evaluAt10n
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - ambev_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "developer"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  ambev.developerevaluation.nosql:
    container_name: ambev_developer_evaluation_nosql 
    image: mongo:8.0    
    environment:
      MONGO_INITDB_ROOT_USERNAME: developer
      MONGO_INITDB_ROOT_PASSWORD: evaluAt10n
    ports:
      - "27017:27017"
    networks:
      - ambev_network
    healthcheck:
      test: ["CMD", "mongo", "--username", "developer", "--password", "evaluAt10n", "--eval", "db.runCommand({ connectionStatus: 1 })"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  ambev.developereevaluation.rabbitmq:
    container_name: ambev_developer_evaluation_rabbitmq
    image: rabbitmq:3.12-management
    environment:
      RABBITMQ_DEFAULT_USER: developer
      RABBITMQ_DEFAULT_PASS: evaluAt10n
    ports:
      - "5672:5672"  
      - "15672:15672"
    networks:
      - ambev_network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

networks:
  ambev_network:
    driver: bridge
